swagger: "2.0"
info:
  title: Social Network API
  description: Social Network API Documentation
  version: 2.1.0
  contact:
    email: treeroot.ir@gmail.com
  license:
    name: MIT
    url: https://github.com/vinhngo1907/v-network/blob/main/LICENSE
host: http://localhost:3000/api/v1/