export const configKeys = {
	HTTP_SERVER_PORT: 'HTTP_SERVER_PORT',
	JWT_SECRET: 'JWT_SECRET',
	JWT_EXPIRATION: 'JWT_EXPIRATION',
	JWT_EXPIRATION_TIME: 'JWT_EXPIRATION_TIME',
	
	POSTGRES_HOST: 'POSTGRES_HOST',
    POSTGRES_PORT: 'POSTGRES_PORT',
    POSTGRES_USER: 'POSTGRES_USER',
    POSTGRES_PASSWORD: 'POSTGRES_PASSWORD',
    POSTGRES_DATABASE: 'POSTGRES_DATABASE',
    
	REDIS_HOST: 'REDIS_HOST',
	REDIS_PORT: 'REDIS_PORT',
	REDIS_PASSWORD: 'REDIS_PASSWORD',
	REDIS_DB: 'REDIS_DB',
	REDIS_EX: 'REDIS_EX',

	HEADER_USER_ID: 'HEADER_USER_ID',
	HEADER_IS_ADMIN: 'HEADER_IS_ADMIN',

	MONGODB_URI: "MONGODB_URI",
	MONGO_PORT: "MONGO_PORT",

	INFLUX_DB_TOEKN: "INFLUX_DB_TOEKN",
	INFLUX_DB_ORG: "INFLUX_DB_ORG",
	INFLUX_DB_BUCKET: "INFLUX_DB_BUCKET",
	INFLUX_DB_URL: "INFLUX_DB_URL",

	CLIENT_URL: "CLIENT_URL",
	MODE: "MODE",
};
