@serverUrl = http://localhost:3001
@adminUrl = http://localhost:3000/api

GET {{serverUrl}}
Content-Type: application/json
###

GET {{adminUrl}}
Content-Type: application/json

###
POST {{serverUrl}}/auth/register
Content-Type: application/json

{
  "account": "vinhtrungngo1907@gmail.com",
  "fullName":"Ngo Trung Vinh",
  "username": "vinhngo97",
  "password": "123456"
}
###

POST {{serverUrl}}/auth/signin
Content-Type: application/json

{
  "account": "vinhngo97",
  "password": "123456"
}
###

PUT {{serverUrl}}/update/2
Content-Type: application/json

{
  "email":"vinhtrungngo@gmail.com",
  "fullname":"Koo kuu"
}

###
GET {{serverUrl}}/notify/hello
###
# GET {{serverUrl}}/user/69568f79-86a2-4e08-bc2b-401337b4de10
GET {{serverUrl}}/user/83c9d434-3e22-4f05-a104-12ff627b92cd
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpbmhuZ285NyIsInVzZXJJZCI6IjgzYzlkNDM0LTNlMjItNGYwNS1hMTA0LTEyZmY2MjdiOTJjZCIsImlhdCI6MTc0NTY1NTAzMywiZXhwIjoxNzQ1NzQxNDMzfQ.0CtsG6tVhNdcI0eYs60FJzww3X61Yh8_4a4Smf7x_gg

###
GET {{serverUrl}}/user?name=vi
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpbmhuZ285NyIsInVzZXJJZCI6IjgzYzlkNDM0LTNlMjItNGYwNS1hMTA0LTEyZmY2MjdiOTJjZCIsImlhdCI6MTc0NTY1NTAzMywiZXhwIjoxNzQ1NzQxNDMzfQ.0CtsG6tVhNdcI0eYs60FJzww3X61Yh8_4a4Smf7x_gg