@serverUrl = http://localhost:3001
@adminUrl = http://localhost:3000/api

GET {{serverUrl}}
Content-Type: application/json
###

GET {{adminUrl}}
Content-Type: application/json

###
POST {{serverUrl}}/auth/register
Content-Type: application/json

{
  "account": "vinhtrungngo1907@gmail.com",
  "fullName":"Ngo Trung Vinh",
  "username": "vinhngo97",
  "password": "123456"
}
###

POST {{serverUrl}}/auth/signin
Content-Type: application/json

{
  "account": "vinhtrungngo1907@gmail.com",
  "password": "123456"
}
###

PUT {{serverUrl}}/update/2
Content-Type: application/json

{
  "email":"vinhtrungngo@gmail.com",
  "fullname":"Koo kuu"
}

###
GET {{serverUrl}}/notify/hello